### ISSUE TITLE
An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by fiy-fiy** [Uminosachi/sd-webui-inpaint-anything#116]
> Due to network reasons, realisticVisionV51 cannot be automatically downloaded_ I have manually downloaded and placed the v51VAE inpainting model in Under 'cache/plugingface/hub', but still unable to use ![image](https://user-images.githubusercontent.com/66582460/284473769-cda30afe-9404-443f-850c-819cfe529613.png) ![image](https://user-images.githubusercontent.com/66582460/284473835-a6d82071-fddc-468e-b035-714d63f9a1a0.png)
![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/66582460/7501a4d3-53ed-423d-b1fb-f9ef39f81fb7)

**Comment by Uminosachi** [comment]
If you are connected to the internet, please try deleting the `models--Uminosachi--realisticVisionV51_v51VAE-inpainting` folder in `~/.cache/huggingface/hub`, and then run Inpainting.

**Comment by fiy-fiy** [comment]
Thank you very much. The problem has been resolved, mainly due to the difference between the format downloaded manually and automatically

**Comment by sun4388** [comment]
fiy-fiy  ,I am encountering the same problem. Do you have a detailed solution process?

**Comment by sun4388** [comment]
> 谢谢。该问题已得到解决，主要是由于手动下载和自动下载的格式不同

怎么解决的？

**Comment by Memodeer** [comment]
I had the same problem. I downloaded pyannote/segmentation-3.0 locally.But this error was reported while running
