### ISSUE TITLE
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'script_args_value'

### ISSUE THREAD

**Issue by OTTIddQd** [Uminosachi/sd-webui-inpaint-anything#120]
I'm trying to make use of Controlnet within inpaint anything and i'm receiving this error:
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'script_args_value'

I've searched for solutions about this but haven't come across any.
I'm a bit of a beginner so I don't know where to start solving this issue.
![2023-12-02 11_38_57](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/152692912/45ca8316-f309-4af1-838a-36404e850d22)
![2023-12-02 11_43_33](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/152692912/fd52c693-3935-41ae-b58e-a96c492289ad)

So far I tried disabling Deforum to see if it makes any difference but so far no luck.
Also, I'm a fan of using UniPC and I noticed it wasn't available in the dropdown menu. Might be another issue all together but figured I make mention. Frankly I'm not able to use UniPC outside of txt2img in general.

I'm making use of A1111 Stable Diffusion (webui-user.bat) if it matters.
If more info about this issue is needed I'm happy to provide

**Comment by Uminosachi** [comment]
I have investigated the cause and it appears that an error is occurring due to the outdated version of stable-diffusion-webui. To resolve this, please update stable-diffusion-webui by using the `git pull origin master` command.

**Comment by OTTIddQd** [comment]
Thank you very much. That solved the issue!
