### ISSUE TITLE
Adding Custom Inpainting Model ID

### ISSUE THREAD

**Issue by lebeastmode** [Uminosachi/sd-webui-inpaint-anything#124]
How do I add custom Inpaiting Model ID. Specifically [majicMIX realistic](https://civitai.com/models/43331?modelVersionId=221343)
Running threw windows.

**Comment by Uminosachi** [comment]
Please save the downloaded model 'majicmixRealistic_v7-inpainting.safetensors' in the 'stable-diffusion-webui/models/Stable-diffusion' folder. Then, restart either webui.bat or webui.sh. Following this, it should appear in the 'Inpainting Model ID' list under the 'Inpainting webui' tab.

**Comment by lebeastmode** [comment]
its showing up  as a checkpoint but not in the model id list
![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/123332023/af07122b-3330-4773-8d34-e2e295066d0c) 

![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/123332023/5611f10a-7b5b-4881-a5cf-7f5099479a2f)

**Comment by Uminosachi** [comment]
The Model ID of the added safetensors file will appear not under the 'Inpainting' tab, but under the 'Inpainting webui' tab.

**Comment by lebeastmode** [comment]
Thanks its there!
