### ISSUE TITLE
can't select self downloaded inpaint mode

### ISSUE THREAD

**Issue by bluelovers** [Uminosachi/sd-webui-inpaint-anything#150]
![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/167966/c9208409-a711-4544-950e-15415f034d8d)

![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/167966/54efa304-14e8-4562-b074-c3b0de5c1bb4)

**Comment by Uminosachi** [comment]
For files with the `.safetensors` extension, you can place them in the `models/Stable-diffusion` folder under the `stable-diffusion-webui` directory. These files will then appear in the Model ID list under the `Inpainting webui` tab (only if the filename contains `inpaint`, case insensitive).

**Comment by bluelovers** [comment]
file already inside of `models\Stable-diffusion\90.Inpainting`

and filename `realisticVisionV60B1_v60B1InpaintingVAE.safetensors` has `inpaint`

**Comment by bluelovers** [comment]
sd webui can see it

**Comment by Uminosachi** [comment]
The inpainting model placed in the models folder of stable-diffusion-webui will not appear under the `Inpainting` tab of Inpaint Anything. Instead, it will be available in the `Inpainting Model ID webui` dropdown list found in the `Inpainting webui` tab, which is located next to the `Cleaner` tab.

**Comment by bluelovers** [comment]
![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/167966/f4ecb8ab-0988-4cd1-99e5-8787d14e7c9d)
