### ISSUE TITLE
[2 Feature Requests] - Save to default image directory option / Send mask to IMG2IMG  "inpaint upload" (for custom model use)

### ISSUE THREAD

**Issue by CCpt5** [Uminosachi/sd-webui-inpaint-anything#21]
Hello! First off thanks for your time/effort creating such a useful app & extension. I've used SAM before w/ a different extensions (that's great in its own right), but I find what you've done here to be quicker for my personal workflow.

I found out about your extension from a post on the SD reddit forum (in case you weren't aware it had been the subject of a popular thread there yesterday) : https://old.reddit.com/r/StableDiffusion/comments/13szvlj/inpaint_anything_uses_segment_anything_cool_a1111/  
  
As for my feature requests: 

1) Option to save images & masks to the default image folder in settings. With the images currently being saved to a folder in the webui extension path it's cumbersome to navigate over there just to move those images back w/ the rest of my generations. It'd be great if perhaps you added a settings page in the main app setting where it'd be possible to change the folder for saving images & masks.  

2) A button in the "Inpaint Anything" tab to send the generated mask to the normal A1111 inpainting page (specifically inpaint upload where you can add an image as a mask). This would allow for custom models. Many of us train models w/ Dreambooth or have downloaded custom models which aren't selectable in the "Inpaint Anything" tab. 

Sending the mask to Controlnet, or incorporating the Controlnet model for inpainting would be a 3rd request - but I would assume that'd be a difficult undertaking. The other two are hopefully possible, and not too time consuming to implement if you find them acceptable for your project. 

Thanks for considering!

**Comment by Uminosachi** [comment]
Thank you for your suggestion. I have implemented your first request. You can switch to the `outputs/img2img-images` directory via the "Inpaint Anything" section found in the "Settings" tab on the Web UI.
As for your second and subsequent requests, I will conduct an investigation to determine their feasibility.

**Comment by Uminosachi** [comment]
If not many users are going to use it, implementing it may not bring much value. So, I will consider this carefully.

**Comment by Ptibouc77** [comment]
I second this idea too, my A1111 is installed on my ssd but my output folder are located on a different hard drive, so it will be nice to have a option to move the outputs folder or to make it imatches the img2img folder set in "Paths for saving" like @CCpt5 said

**Comment by Uminosachi** [comment]
I've updated the logic to use the web UI's img2img output path setting when "img2img-images" is selected as the save folder in Inpaint Anything settings.

* Inpaint Anything section in Settings tab:
![0eb38fc9-990d-43f8-81be-ecd93836d602_crop](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/49424133/dedb5d9a-6dab-42a6-9b1c-13467681a186)

* Paths for saving section in Settings tab:
![33a46844-1827-4a78-b637-55fe6264b97e_crop](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/49424133/4b50a5cc-7509-4784-955e-9ca6816464d4)

**Comment by Uminosachi** [comment]
Since these two features have already been implemented, I am closing this issue.
