### ISSUE TITLE
lama cleaner

### ISSUE THREAD

**Issue by BoBoBiBop** [Uminosachi/sd-webui-inpaint-anything#31]
It can't find lama cleaner, it tells me in read the readme to install manually. Any ideas on what could be occurring.

**Comment by magestyx** [comment]
Go here and install via pip or there's a Windows 5-minute installer you can purchase for $5.
I had issues and errors with the pip method so finally used the purchased installer and it worked.
https://lama-cleaner-docs.vercel.app/

**Comment by Uminosachi** [comment]
Lama Cleaner can be installed by [pip](https://pypi.org/project/lama-cleaner/).

For Windows:
```
 .\venv\Scripts\activate
pip install lama-cleaner
deactivate
```
