### ISSUE TITLE
Any way to use already downloaded inpainting models from standart webui models path?

### ISSUE THREAD

**Issue by DaveScream** [Uminosachi/sd-webui-inpaint-anything#33]
bump

**Comment by Uminosachi** [comment]
As of v1.4.1, the "Send to img2img Inpaint" button has been added to the Mask only tab. This enables users to send a mask image directly to the "Inpaint Upload" section on the img2img tab.
Consequently, you can now utilize the existing inpaint model on the Web UI using the created mask.

**Comment by DrMacabre** [comment]
is there a way to use the inpainting models from inpaint anything as inpaint models in the webui? can't find where they are saved, i wanted to try if i could merge some of them.

**Comment by Uminosachi** [comment]
The 'Inpainting webui' tab, which enables the use of the inpainting model saved in the web UI models directory, has been implemented. Therefore, this issue will be closed.
