### ISSUE TITLE
Unmasked regions (whole picture) have small changes

### ISSUE THREAD

**Issue by DaveScream** [Uminosachi/sd-webui-inpaint-anything#34]
why?

**Comment by Uminosachi** [comment]
The mask image is also utilized as input for the Inpainting model. However, there's a possibility that the area outside the mask may experience slight changes.
In consideration of this, in v1.4.2,  I added a checkbox labeled "Mask area Only". When this checkbox is selected, modifications will be applied exclusively within the mask area.
