### ISSUE TITLE
Every inpainting model 'works' but gives a *.safetensors not found error

### ISSUE THREAD

**Issue by magestyx** [Uminosachi/sd-webui-inpaint-anything#35]
I have this extension working now - really cool stuff.
But every single Inpainting Model shows an error loading the vae or unet or text_encoder safetensors file.  Some are missing and only have the bin file, yes, but even if I find the safetensors and put it into the vae folder for the inpainting model, it still says the file can't be found.
These are the messages appearing when I run the extension on different models - just 2 lines for each one almost immediately after Run Inpainting is clicked:

runwayml/stable-diffusion-inpainting
text_encoder\model.safetensors not found

stabilityai/stable-diffusion-2-inpainting
vae\diffusion_pytorch_model.safetensors not found

Uminosachi/dreamshaper_5-inpainting
vae\diffusion_pytorch_model.safetensors not found

saik0s/realistic_vision_inpainting
vae\diffusion_pytorch_model.safetensors not found

The saik0s one for example has a version with all the safetensors available here: 
https://huggingface.co/saik0s/realistic_vision_inpainting/discussions/2

I downloaded all 3 safetensors (vae, unet, text_encoder) and placed them in the respective directories.
I still get the errors.

Any ideas?

**Comment by Uminosachi** [comment]
That log also appears in my environment, and I find it puzzling since the file does exist. Nonetheless, the Inpaint process itself works without any issues, so it doesn't bother me too much.

**Comment by JonyTianming** [comment]
When installing previously, everything that needs to be installed shows that the installation is 100% complete.
But,I have a similar situation：

stabilityai/stable-diffusion-2-inpainting
text_encoder\model.safetensors not found

text_encoder\model.safetensors not found
Error no file named config.json found in directory C:\Users\J.........inpainting\snapshots\6ba40839c3c171123b2b863d16caf023e297abb9\unet.

AND This has happened before：
stabilityai/stable-diffusion-2-inpainting
unet\diffusion_pytorch_model.safetensors not found
We have no connection or you passed local_files_only, so force_download is not an accepted option.

**Comment by sean-kang** [comment]
I see the inpainting and lama models are downloaded in cache directory. This is an unreliable way to store a persistent data such as checkpoint models since they can be removed anytime. Also, it is inconsistent with where the model files are stored in webui.

To be honest, I think the inpainting feature of this extension is redundant because webui already has inpainting UI and the users are likely to have their own inpainting models. It will be better if the segment anything feature is incorporated into webui's inpainting UI.

**Comment by Uminosachi** [comment]
The display issue 'safetensors not found' has been resolved by setting `local_files_only=True` in the diffusers' `from_pretrained` function. Therefore, this issue will be closed.
