### ISSUE TITLE
Stable Diffusion install not working after installing

### ISSUE THREAD

**Issue by mtsweir** [Uminosachi/sd-webui-inpaint-anything#40]
I followed the instructions to install this, then when I run SD it gives me this error message:

**Console error message:**
![console](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/4976660/aa73165a-4fbd-4edf-a7c5-abcbd02e9263)

**GFX Card Driver:**
![driver](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/4976660/4eb73bdb-b75c-49bd-aa4a-c4cba7cc1712)

**Comment by Uminosachi** [comment]
Could you please confirm whether [CUDA](https://developer.nvidia.com/cuda-toolkit-archive) and [cuDNN](https://developer.nvidia.com/rdp/cudnn-download) have been installed?

**Comment by mtsweir** [comment]
Thanks for getting back, how would I be able to check?

**Comment by Uminosachi** [comment]
I use the command `nvidia-smi` to check the driver version, GPU card, and memory.

**Comment by mtsweir** [comment]
Here's a screenshot using the command `nvidia-smi`

![Screenshot 2023-06-03 124748](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/4976660/51444659-b92c-438c-8744-9ded6b79b631)

**Comment by Uminosachi** [comment]
It seems to have been resolved by the installation of CUDA and cuDNN drivers, so I will close this issue.
