### ISSUE TITLE
can't download any inpainting model

### ISSUE THREAD

**Issue by huangkun1985** [Uminosachi/sd-webui-inpaint-anything#43]
when i clicked "run inpainting" button, it started to download some files, which were some shortcuts instead of the real files, and then an "OSError" showed, what can i do? can i just get the links of the files instead of downloading for the control panel?

**Comment by Uminosachi** [comment]
I've uploaded the fix that resume when inpainting model fails to download, please git pull and try it out.

**Comment by Uminosachi** [comment]
Closing this issue as I have addressed the model download resume issue and added instructions on caching the model in the README.
