### ISSUE TITLE
add sd-webui-inpaint-anything to index

### ISSUE THREAD

**Issue by w-e-w** [Uminosachi/sd-webui-inpaint-anything#46]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/83
add sd-webui-inpaint-anything
https://github.com/Uminosachi/sd-webui-inpaint-anything
@Uminosachi
we received a request to add your extension https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/issues/82
can you confirm if the description and the tags are to your liking

**Comment by Uminosachi** [comment]
Please utilize the description and tags provided below. If "inpainting" cannot be applied as a tag, please use "editing".

"description": "The Inpaint Anything extension performs SD inpainting, cleaner, ControlNet inpaint, and sending a mask to img2img, using a mask selected from the segmentation output of Segment Anything."
"tags": ["tab", "inpainting"]
