### ISSUE TITLE
How can I further select areas to inpaint after creating a mask?

### ISSUE THREAD

**Issue by timmyhk852** [Uminosachi/sd-webui-inpaint-anything#48]
After I created a mask from the inpaint anything, I want to draw something else to further mask which however doesnt have any effect.

What should I do?

**Comment by timmyhk852** [comment]
![aaa](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/132486967/ebec3c4d-0c11-49e6-b76e-db30510ebfad)
For example, I want to change the foot (in the pink area), but if I select the pink area, this will affect other things which are also in pink area

**Comment by Uminosachi** [comment]
This is because the Segment Anything model produces such segmentation results. There are three versions of the SAM model, each providing different segmentation outcomes. Therefore, trying various models is advisable for obtaining different results.

**Comment by timmyhk852** [comment]
so, the solution should be "Send to inpaint"? but will you add this function?
Also, will you also add "batch count" function so that I can generate 3-5 images from the same mask to compare which one is better?

**Comment by Uminosachi** [comment]
In the bottom right corner, there is a `Trim mask by sketch` button that allows you to subtract the sketched part from the generated mask. This feature enables you to narrow down the area of the mask.
The second "batch count" function, I will consider the necessity and implementation method.

**Comment by timmyhk852** [comment]
thank you :)
