### ISSUE TITLE
reload everything after everytime i used inpainting

### ISSUE THREAD

**Issue by YanXiaoAI** [Uminosachi/sd-webui-inpaint-anything#49]
thank you for you work, this one works terrific!!! much better than the old workflow by use SAM

The problem I fond is that every time after i used inpainting, the whole webui reload everything again, even though it doesn't take me too much, but still a bit annoying~ is this my problem or this plugin has some other settings i don't know?

![1](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/132332609/b6aafb64-ecf3-4449-9cca-20b4cdcb3ad1)

![微信截图_20230611012204](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/132332609/a47254ee-477d-4a4f-838d-de15397587e6)

**Comment by Uminosachi** [comment]
The Inpainting, Cleaner and Segment Anything functions do not utilize the Stable Diffusion checkpoint, located in the upper left of the Web UI, and as such, it is intentionally unloaded and reloaded in the program. Therefore, this is a standard log.

**Comment by YanXiaoAI** [comment]
okay,i see, thank you~

**Comment by Uminosachi** [comment]
Unloading and reloading the model is performed intentionally to free up VRAM. Therefore, this issue will be closed.
