### ISSUE TITLE
[Feature Request] - Add support for new model "Segment Anything in High Quality" - (Model Checkpoints now available)

### ISSUE THREAD

**Issue by CCpt5** [Uminosachi/sd-webui-inpaint-anything#50]
Perhaps an obvious request, but the checkpoints for "Segment Anything in High Quality" were made available for download w/in the past 24hrs. Hoping these can be added as options in "Inpaint-Anything":

https://github.com/SysCV/sam-hq

https://github.com/SysCV/sam-hq/issues/5 - (Extra downloading links)

Thanks!

**Comment by Uminosachi** [comment]
Thank you for your request. I am already working on it, but it's using more VRAM than Facebook's SAM, and I am currently investigating the issue.

**Comment by Uminosachi** [comment]
HQ-SAM is supported in v1.7.1, but it might not be as user-friendly due to its higher VRAM usage.
