### ISSUE TITLE
Error when creating mask from segment anything image

### ISSUE THREAD

**Issue by zakbluefb** [Uminosachi/sd-webui-inpaint-anything#52]
![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/40908935/850e597c-2510-40da-bd3b-5a7c2251f03a)
I have a problem when trying to go from the segmented image to creating the mask. I see the progress bar in the webui and an image flashes up but it doesn't give me a masked image.

**Comment by Uminosachi** [comment]
The version of [AUTOMATIC1111's stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui.git) appears to be outdated. Given that the Gradio package is also old, this could potentially lead to errors. I recommend executing a git pull within the stable-diffusion-webui directory, deleting the venv directory, and then restarting the Web UI.

```
git pull origin master
```

**Comment by zakbluefb** [comment]
That was it! It's now working brilliantly. Thank you!!
![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/40908935/eddb7731-b760-45bd-9b6b-152ea24e323b)

**Comment by Uminosachi** [comment]
This issue has been resolved by upgrading the stable-diffusion-webui and will now be closed.
