### ISSUE TITLE
VAE not loading on webui start

### ISSUE THREAD

**Issue by dhwz** [Uminosachi/sd-webui-inpaint-anything#61]
See https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10355, same issue also happening if [sd-webui-inpaint-anything](https://github.com/Uminosachi/sd-webui-inpaint-anything) is installed and enabled, please check how they resolved it for the vram-estimator extension.

**Comment by Uminosachi** [comment]
Thank you for your bug report. The issue has been resolved in the latest code.
