### ISSUE TITLE
Installing requirements for lama_cleaner Can't install lama-cleaner. Please follow the readme to install manually

### ISSUE THREAD

**Issue by alexgilseg** [Uminosachi/sd-webui-inpaint-anything#63]
So when I try to lead SD after insatlling this I get the following error:

Installing requirements for lama_cleaner
Can't install lama-cleaner. Please follow the readme to install manually

I have read through the readme and there is nothing that shows me how to install this manually to get it to work. Thanks!

**Comment by Uminosachi** [comment]
You can install it individually using the method provided below, but be aware that the Python version used may be outdated.

https://github.com/Uminosachi/sd-webui-inpaint-anything/issues/2#issuecomment-1571761053

**Comment by alexgilseg** [comment]
I actually atempted that before and installing llama cleaner that way to A1111 it gives the following error:

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'd:\\sd\\stable-diffusion-webui\\venv\\lib\\site-packages\\bidict-0.22.1.dist-info\\METADATA'

**Comment by Uminosachi** [comment]
It's possible that your package is corrupted. I recommend deleting the venv folder in the stable-diffusion-webui folder, then run webui.bat to reinstall the package from scratch.

**Comment by DOGMANTC** [comment]
so did it work for you?

**Comment by Uminosachi** [comment]
I have included lama_cleaner in the repository, so I am closing this issue.
