### ISSUE TITLE
Segmented image disappears in a split second

### ISSUE THREAD

**Issue by prabhjot5877** [Uminosachi/sd-webui-inpaint-anything#65]
Whenever i run segement anything, it does work exactly like it should but the image on right side only comes up for some milliseconds and then it's gone. I did reinstall the extension, disabled all other extensions and restarted webui but still same problem. Any solution?

**Comment by Uminosachi** [comment]
In the past, there have been instances where the sketch function did not function properly when privacy protection extensions were enabled in browsers like Google Chrome and Microsoft Edge. While it's uncertain if this is related to your current issue, you could try disabling these extensions as a potential solution.

**Comment by Uminosachi** [comment]
The gradio package in the venv might be outdated. Consider deleting the `venv` folder located within stable-diffusion-webui, then launch `webui.bat` or `webui.sh` and reinstall the gradio package in the new venv.

**Comment by Uminosachi** [comment]
I have fixed for the section that appeared to be causing the issue in the latest version of the code.

**Comment by prabhjot5877** [comment]
Thanks for the fix mate. Everything's working perfect again. Great work

**Comment by Uminosachi** [comment]
Since the problem where the segmentation image disappears momentarily had been fixed, this issue will be closed.
