### ISSUE TITLE
Semantic segmentation is not very accurate

### ISSUE THREAD

**Issue by qihua** [Uminosachi/sd-webui-inpaint-anything#66]
Dear author, thank you for your project, but the semantic segmentation is not very accurate, and the face and hair cannot be well segmented. Is there any solution?
![1688001118220](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/11694605/8a483cf7-e69d-49c3-b074-99987787b101)

**Comment by Uminosachi** [comment]
Altering the SAM model will affect the segmentation pattern. Therefore, it's encouraged to experiment with various models.

Selectable SAM models:
- sam_vit_h_4b8939.pth
- sam_vit_l_0b3195.pth
- sam_vit_b_01ec64.pth
- sam_hq_vit_h.pth
- sam_hq_vit_l.pth
- sam_hq_vit_b.pth
- FastSAM-x.pt
- FastSAM-s.pt

**Comment by qihua** [comment]
8 models have been tried, are not very ideal

**Comment by qihua** [comment]
Can you add some points to help choose？

**Comment by Uminosachi** [comment]
I won't know the result until I make an inference, but it seems that anime-style images tend not to yield good results.

**Comment by Uminosachi** [comment]
The `Anime Style (Up Detection, Down mask Quality)` checkbox has increased the segment detection. Therefore, this issue will be closed.
