### ISSUE TITLE
Models download locations unclear 

### ISSUE THREAD

**Issue by littleboot** [Uminosachi/sd-webui-inpaint-anything#69]
I'm looking for the location were the models are stored for this plugin. The reason being I have an unstable internet connection (mobile data) that requires a manual manual intervention every 2GB. So the connection is lost temporary. I'm not able to download models >2GB using the plugin itself because when it disconnects it needs to restart the download. using an external download manager I can manually download the models because it can resume downloads after connection failure.

I found the SAM models are stored here (The readme says models are stored in the `models` dir, this is not helpful I assumed the main models directory because the 'model' folder inside the plugin folder is only created after the download is started (please make this more clear in the readme):
```sd.webui\webui\extensions\sd-webui-inpaint-anything\models```

by default the `sam_vit_l_0b3195.pth` gets selected I would like to have an option to change the default to sam_vit_h_4b8939.pth 

**Inpainting Models location???**
I can not find out how to download the inpainting models manually and were to place them. Can someone help me with this?

It looks like these are downloaded to:
```C:\Users\admin\.cache\huggingface\hub\models--stabilityai--stable-diffusion-2-inpainting\snapshots\6ba40839c3c171123b2b863d16caf023e297abb9\text_encoder```

This folder contains a symbolic link to:
C:\Users\admin\.cache\huggingface\hub\models--stabilityai--stable-diffusion-2-inpainting\blobs

I really don't like that the inpainting models seem to be stored outside the sd.webui folder. This makes the webui no longer portable...
If possible please change this

**Comment by Uminosachi** [comment]
For any models you download in the Inpainting tab, we utilize the caching system provided by Hugging Face Hub. Should you wish to change the download location, you can adjust an environment variable.
For more information on managing cache, you may refer to the [Hugging Face Hub guide](https://huggingface.co/docs/huggingface_hub/guides/manage-cache).
> The <CACHE_DIR> is usually your user’s home directory. However, it is customizable with the cache_dir argument on all methods, or by specifying either HF_HOME or HUGGINGFACE_HUB_CACHE environment variable.

**Comment by littleboot** [comment]
Thank you for the quick response, I had a look at the link you provided but this does not solve my problem nut it explains the download location and folder structure. 
It is not clear to me if it is possible to download the "Inpainting Models" manually and were I should put these files.
Is it possible to run the download command with an increased timeout?

For example I would like to download the "Uminosachi/dreamshaper_6Inpainting" manually.
These files are downloaded from: https://huggingface.co/Uminosachi/dreamshaper_6Inpainting/tree/main
Which is failing because of my 2GB download limit (timeout):
![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/17753602/0bde6cca-b2a2-44af-83e5-b09abaf25ec6)

The best solution for me would be to increase the download timeout so I can restore the connection and resume the download.
(It takes me about 20 sec to apply for an additional 2GB at my mobile provider.)

A workaround that may work for me is to download the big files that are failing to download manually, rename them to their hash and put them in the "models--Uminosachi--dreamshaper_6Inpainting\blobs" folder.
I think this might work so I will be trying this next.

**Comment by littleboot** [comment]
Managed to get it to work, by manually downloading the required big files and renaming them to their hash and placing them in the blobs folder.

example:
```
Retrieve the model repo name from the sd.webui prompt and look it up an hugginfaces.

For example the "Uminosachi/dreamshaper_6Inpainting" model:
https://huggingface.co/Uminosachi/dreamshaper_6Inpainting
Go to files and versions

Find the file that failed to download based uppon its file size.

Download it manually: https://huggingface.co/Uminosachi/dreamshaper_6Inpainting/tree/main/unet

Use powershell with "get-filehash" to get the file hash.


Copy the hash: 
E573F86C5C31BFFE337A29E40B48C03AE10149F5C2995C61439A03D7C8477CBE

Convert it to lower case (https://convertcase.net/):
e573f86c5c31bffe337a29e40b48c03ae10149f5c2995c61439a03d7c8477cbe

Rename the file to the hash (note also remove file extension name)

Place it is the blobs folder: 
C:\Users\admin\.cache\huggingface\hub\models--Uminosachi--dreamshaper_6Inpainting\blobs
```
