### ISSUE TITLE
ERROR - FIND was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by modernbaby** [Uminosachi/sd-webui-inpaint-anything#70]
I got following errors when I click 'Run Segment Anything' 

2023-07-02 09:24:33,263 - Inpaint Anything - INFO - input_image: (1380, 1000, 3) uint8
2023-07-02 09:24:36,724 - Inpaint Anything - INFO - SamAutomaticMaskGenerator sam_vit_l_0b3195.pth
2023-07-02 09:24:38,271 - Inpaint Anything - **ERROR - FIND was unable to find an engine to execute this computation**
Loading weights [c6fe5d4a3e] from /home/james/stable-diffusion-webui/models/Stable-diffusion/Realistic_Vision_V2.0/realisticVisionV20_v20NoVAE.ckpt
Creating model from config: /home/james/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /home/james/stable-diffusion-webui/models/VAE/Anything-V3.0.vae.pt
Applying attention optimization: xformers... done.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
Model loaded in 4.1s (create model: 0.7s, apply weights to model: 1.5s, apply half(): 0.5s, load VAE: 0.5s, move model to device: 0.6s, load textual inversion embeddings: 0.3s).

Can someone help me explain this problem?

**Comment by Uminosachi** [comment]
When I searched across different repositories for the same error message, It seems that the PyTorch and CUDA versions are incompatible.
To reinstall PyTorch, delete the `venv` folder located inside the stable-diffusion-webui folder, and run `webui.bat` or `webui.sh` for automatic installation. If the CUDA version isn't compatible, consider installing the appropriate version from the [NVIDIA](https://developer.nvidia.com/cuda-downloads) page.

https://github.com/Megvii-BaseDetection/YOLOX/issues/1642

**Comment by modernbaby** [comment]
I solved this problem, it was indeed caused by the CUDA version, Thank you.
