### ISSUE TITLE
How to zoom in Segment Anything Image with canvas zoom ?

### ISSUE THREAD

**Issue by maxryan02** [Uminosachi/sd-webui-inpaint-anything#74]
How to zoom in Segment Anything Image with canvas zoom ?

**Comment by Uminosachi** [comment]
The canvas zoom function is currently unsupported. I believe the demand for it might be minimal since you can create a mask simply by pointing with a sketch.

**Comment by Uminosachi** [comment]
Considering the challenge of sketching small segments, the latest update now includes the canvas zoom function, including Fullscreen support. You can enable this feature by hovering your mouse over the image and pressing the `S` key for Fullscreen mode.

**Comment by maxryan02** [comment]
it still work , i download the lastest but nothing happen.

**Comment by Uminosachi** [comment]
If `Mouse over image: Press S key for Fullscreen mode, R key to Reset zoom` is displayed in the upper right corner of the 'Inpaint Anything' tab, then it is supported.

**Comment by maxryan02** [comment]
> 

i'm try it on "segment anything image" to create mask something tiny but it not work :(. So sad . Hope one day you have free time to update it. Now i zoom browser to 200% and mask it.

**Comment by daswer123** [comment]
Guys in one of the communities gave a link to your extension, I can add support for your extension as it is done for controlNet, Latent Couple, Regional prompter.

**Comment by Uminosachi** [comment]
I appreciate your work on the canvas-zoom extension. I've tested it and encountered two issues:

Image Height Change: Even after setting the style attribute for height as '480' (style(height=480)), the image height appears to be changing.

Coordinate Inconsistency: I'm finding a mismatch between the coordinates I'm drawing on and the ones I'm retrieving later. This might be tied to the issue of the changing image height.

**Comment by Uminosachi** [comment]
@daswer123
Additional Information: This issues occurs within the 'dev' branch of the web UI.

**Comment by daswer123** [comment]
https://github.com/richrobber2/canvas-zoom/issues/88#issuecomment-1666447332

I'm just about to transfer all modifications to the new version of gradio, maybe the problem will go away.

**Comment by Uminosachi** [comment]
Canvas zoom functionality is already available, so this issue is now closed.
