### ISSUE TITLE
[Feature Requests]APIs support

### ISSUE THREAD

**Issue by zhuqingsong59** [Uminosachi/sd-webui-inpaint-anything#81]
can i inpaint picture by api?
input picture get Segment picture

**Comment by Uminosachi** [comment]
I'm considering handling it. I will announce when it is ready.

**Comment by zhuqingsong59** [comment]
thanks alot

**Comment by Uminosachi** [comment]
I have implemented a library that enables segmentation and mask generation using sketches from other extensions within the web UI.

https://github.com/Uminosachi/sd-webui-inpaint-anything/blob/main/README_DEV.md

**Comment by wen2034** [comment]
Can it be made into a web API

**Comment by Uminosachi** [comment]
> Can it be made into a web API

At this time, there are no plans in place to develop a web API.
