### ISSUE TITLE
Feature request: batches

### ISSUE THREAD

**Issue by rugabunda** [Uminosachi/sd-webui-inpaint-anything#83]
having to manually click 'run inpainting' for every iteration is time consuming, requiring the user to be present at all times, would be great to see an option to do them in batches, this would save time by 90%+

Thanks for your time!

**Comment by Uminosachi** [comment]
I've added an `Iteration` slider below the `Run Inpainting` button. By adjusting this slider, you can run inpainting multiple times with different seeds. Please update and give it a try.

**Comment by Uminosachi** [comment]
Batch execution (iterations slider) for inpainting is already supported, so this issue is now closed.
