### ISSUE TITLE
Inpaint only still changing the entire image

### ISSUE THREAD

**Issue by masterzed11** [Uminosachi/sd-webui-inpaint-anything#85]
im selecting "Inpaint only" and its still changing the entire image,

**Comment by Uminosachi** [comment]
I have verified that the entire image change when the `inpaint` option is selected in the 'ControlNet Preprocessor'. However, I observed no changes when the `inpaint_only` option is selected.

I will consider the necessary measures to prevent the entire image from changing when `inpaint` is selected.

**Comment by masterzed11** [comment]
ty it works

**Comment by Uminosachi** [comment]
Please wait a little while to confirm as I am trying to make this together with other fix.

**Comment by Uminosachi** [comment]
A fix has been uploaded to prevent the entire image from changing when `inpaint` is selected.
