### ISSUE TITLE
Where to put file "FastSAM-x.pt" in ?

### ISSUE THREAD

**Issue by AIchenkai** [Uminosachi/sd-webui-inpaint-anything#89]
After i installed inpaint-anything extension by offline method, putting dowloaded filefold in extensions of sd-webui, i cant download SAM models.
When i chose FastSAM-x.pt and click "Download model", it raise "Remote end closed connection without response".
So, i download FastSAM-x.pt form Uminosachi/FastSAM in huggingface manually, may i ask where to put the file  FastSAM-x.pt in ?

**Comment by Uminosachi** [comment]
The path for the Segment Anything model's storage folder is as follows:

For Windows:
```
stable-diffusion-webui\extensions\sd-webui-inpaint-anything\models
```
For Linux:
```
stable-diffusion-webui/extensions/sd-webui-inpaint-anything/models
```
