### ISSUE TITLE
It is not convenient to work with the finished image

### ISSUE THREAD

**Issue by mikheys** [Uminosachi/sd-webui-inpaint-anything#90]
Could you tell me why there is no possibility to zoom or drag the image to another place at the bottom, only the save button. It is inconvenient to work with a finished image. I would like to have the opportunity without opening the catalog to take a closer look at the image and drag it up for further editing.

**Comment by Uminosachi** [comment]
The output image now also supports zoom and reset functions using the `S` and `R` keys, similar to the mask image, and in Chrome or Edge browsers, you can drag and drop the output image to the input image area.

**Comment by Uminosachi** [comment]
I have supported zooming and listing finished images through a gallery view. This issue is now closed.
