### ISSUE TITLE
inpaint_anything.py does not have get_max_models_num

### ISSUE THREAD

**Issue by fu-jianhua** [Uminosachi/sd-webui-inpaint-anything#98]
Error executing callback ui_tabs_callback for D:\projects\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py
Traceback (most recent call last):
  File "D:\projects\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\projects\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 822, in on_ui_tabs
    if cn_enabled and sam_dict["cnet"].get_max_models_num() > 1:
AttributeError: module 'extensions.sd-webui-controlnet.scripts.external_code' has no attribute 'get_max_models_num'

After adding the paint anything extension, there is no paint in the SD menu bar and an error is reported, Please help me

**Comment by Uminosachi** [comment]
It appears that the version of the `sd-webui-controlnet` extension you are using is outdated. To resolve this issue, you may want to update the extension by following these steps:

* Launch `webui.bat` and navigate to the `Extensions` tab in the Web UI.
* Click on `Check for updates`.
* If an update is available, click on `Apply and restart UI` to complete the update process.

**Comment by fu-jianhua** [comment]
The problem has been solved, thank you very much
