### ISSUE TITLE
ZeroDivisionError when using anything other than "Inpainting". (ie: Inpainting WebUI, ControlNet, etc, all fail)

### ISSUE THREAD

**Issue by phleshdef** [Uminosachi/sd-webui-inpaint-anything#99]
I'm using Automatic1111 1.6 (the newest release).

Reproducing this is simple. 

Load an image,
Run Segment Anything.
Choose your area you want to Mask.
Click Create Mask.
Enter your prompts.
Click Run Inpainting.

Using the regular Inpainting approach (The first tab), it works fine. 
If I switch to Inpainting webui or ControlNet Inpaint, I get this error. 

I know with any inpainting tool, this can happen if there is no mask.... but obviously I have one and the regular inpainting tab recognizes it. 

I have the most up to date versions of Automatic1111 and Inpaint Anything extension. I have tried a few different inpainting base models and that doesn't seem to be the problem. 

Any guidance here is greatly appreciated.  

![image](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/34211398/b0c14ce0-cfc1-438a-9263-a1f5a81bceb7)

**Comment by Uminosachi** [comment]
I realized there was a section running that was not necessary, so I have corrected it. To apply the fix, please update the extension by navigating to the `Extensions` tab, then click on `Check for updates`, followed by `Apply and restart UI`.

**Comment by phleshdef** [comment]
@Uminosachi Thank you for the timely response, I just did a quick test and it seems to be working great now.

**Comment by Uminosachi** [comment]
This issue has been fixed, so I am closing it.
